###11
POST http://localhost:8000/register
Content-Type: application/json

{
    "username":"11",
    "password":"11",
    "email":"rmsah12@naver.com"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "username":"11",
    "password":"11"
}

###
DELETE http://localhost:8000/u/unregister
Content-Type: application/json

{
    "username":"11",
    "password":"11"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "username":"11",
    "password":"11"
}